In [1]:
import numpy as np 

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
lst = [1,2,3,4]
arr = np.array([1,2,3,4])
print(lst)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


## Creating arrays

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array((1, 2, 3))

## Dimensions

In [11]:
#0-D Arrays
arr = np.array(42)

print(arr)

42


In [12]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [13]:
# 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
# 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# Check Number of Dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
# Higher Dimensional Arrays
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Array Indexing

In [19]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

1
2


In [20]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [21]:
# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr 


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr[0, 1]

2

In [23]:
arr[1, 4]

10

In [24]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [26]:
arr[2,3]

9

In [30]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [31]:
# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

10


In [32]:
# Slicing 

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [33]:
print(arr[4:])

[5 6 7]


In [34]:
print(arr[:4])

[1 2 3 4]


In [35]:
print(arr[-3:-1])

[5 6]


In [36]:
# step
print(arr[1:5:2])

[2 4]


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [38]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [39]:
# shaping 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [40]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print( arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [41]:
# reshaping 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [47]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [49]:
# join 
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [50]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [54]:
a = np.zeros((2,2))
print(a) 

[[0. 0.]
 [0. 0.]]


In [55]:
b = np.ones((3,3))    
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
5*b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [57]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [60]:
d = np.eye(3)
print(d)  
# Return a 2-D array with ones on the diagonal and zeros elsewhere

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
e = np.random.random((2,2)) 
print(e)

[[0.90503158 0.52067379]
 [0.72893689 0.89385908]]


In [62]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[10,20,30],[40,50,60]])
b+a

array([[11, 22, 33],
       [44, 55, 66]])

In [63]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [64]:
a - b 

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [65]:
np.subtract(a,b)

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [66]:
a * b

array([[ 10,  40,  90],
       [160, 250, 360]])

In [67]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [68]:
a / b 

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [69]:
np.divide(a,b)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [70]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [71]:
np.sqrt(a*a)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [72]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

In [73]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [74]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [77]:
print(x.dot(y))
print("________________")
print(np.dot(x, y))

[[19 22]
 [43 50]]
________________
[[19 22]
 [43 50]]


In [78]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
import matplotlib.pyplot as plt
img = plt.imread("/content/marguerite-729510__340.jpg")
plt.imshow(img)

In [ ]:
type(img)

In [ ]:
img

In [ ]:
img.shape

In [ ]:
plt.imshow(img[50:200,150:])